name: "Get Key Vault Secrets"
description: "Retrieve one or more secrets from an Azure Key Vault"
inputs:
  keyvault:
    description: "Name of the Azure Key Vault"
    required: true
  secrets:
    description: "Name of the secret(s) to be fetched"
    required: true
runs:
  using: "composite"
  steps:
    - name: Azure CLI script
      id: get-secrets
      shell: bash
      env:
        KEYVAULT: ${{ inputs.keyvault }}
        SECRETS: ${{ inputs.secrets }}
      run: |
        for i in ${SECRETS//,/ }
        do
          echo "KEYVAULT: $KEYVAULT"
          echo "SECRET: $i"
          VALUE=$(az keyvault secret show --vault-name $KEYVAULT --name $i --query value --output tsv)
          #echo "::add-mask::$VALUE"
          echo "SECRET VALUE: $VALUE"
          echo "::set-output name=$VALUE::$VALUE"
        done
    - name: TEST STEP
      shell: bash
      run: |
        echo "TEST VALUE: ${{ steps.get-secrets.outputs.my-test-secret }}"
